# Default compose file for development and production.
# Should be used directly in development.
# Automatically loads `docker-compose.override.yml` if it exists.
# No extra steps required.
# Should be used together with `docker/docker-compose.prod.yml`
# in production.

version: "3.8"
services:
  web:
    build:
      context: .
      args:
        DJANGO_ENV: production
    depends_on:
      db:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    ports:
      - "8123:8000"
    volumes:
      - django-static:/var/www/django/static
    environment:
      DJANGO_DATABASE_HOST: db
    command: python -Wd manage.py runserver 0.0.0.0:8000

  telegram:
    build:
      context: .
      args:
        DJANGO_ENV: production
    depends_on:
      db:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    volumes:
      - django-static:/var/www/django/static
    environment:
      DJANGO_DATABASE_HOST: db
    command: python manage.py start_polling

  migrations:
    build:
      context: .
      args:
        DJANGO_ENV: production
    depends_on:
      db:
        condition: service_started
    volumes:
      - django-static:/var/www/django/static
    environment:
      DJANGO_DATABASE_HOST: db
    command: python manage.py migrate

  db:
    image: postgres:15.3-alpine3.18
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  django-static:
