# Generated by Django 4.2.4 on 2023-08-18 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUserModel',
            fields=[
                ('tg_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram user ID')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('is_bot', models.BooleanField(default=False, verbose_name='BOT')),
                ('language_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Language Code')),
                ('token', models.CharField(blank=True, max_length=50, null=True, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Tg Notification Bot User',
                'verbose_name_plural': 'Tg Notification Bot Users',
            },
        ),
        migrations.CreateModel(
            name='TelegramTokenUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, verbose_name='Токен')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Токен для бота',
                'verbose_name_plural': 'Токены для бота',
            },
        ),
    ]
